title: VC's Notes
description: Notes on GTM, marketing, career and other side quests
url: "https://varunchoraria.com"
baseurl: ""
timezone: Asia/Kolkata
markdown: kramdown
highlighter: rouge
permalink: /:slug/
sass:
  style: compressed
  sourcemap: never
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: ""
      type: "posts"
    values:
      layout: entry
      section_name: Note
