#!/usr/bin/env python3
"""Refresh _data/quest_releases.yml from GitHub.

Releases first. If a repo has none, fall back to its recent commits so a project
page is never empty. Reads the repo list from _data/quests.yml (any entry with a
`repo:` key), so adding a project needs no edit here.

    python3 _scripts/refresh_quests.py

Auth: uses GH_TOKEN or GITHUB_TOKEN if set. Private repos need a token that can
read them; repos that return 403/404 are skipped with a warning rather than
failing the run.
"""
import json, os, re, subprocess, sys, urllib.error, urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUESTS = os.path.join(ROOT, '_data/quests.yml')
OUT = os.path.join(ROOT, '_data/quest_releases.yml')
OWNER = 'vcxcvii'
MAX_ENTRIES = 5
TOKEN = os.environ.get('GH_TOKEN') or os.environ.get('GITHUB_TOKEN') or ''


def api(path):
    req = urllib.request.Request(f'https://api.github.com/{path}',
                                 headers={'Accept': 'application/vnd.github+json',
                                          'User-Agent': 'quest-refresh'})
    if TOKEN:
        req.add_header('Authorization', f'Bearer {TOKEN}')
    try:
        with urllib.request.urlopen(req, timeout=20) as r:
            return json.load(r)
    except urllib.error.HTTPError as e:
        print(f'  skip {path}: HTTP {e.code}', file=sys.stderr)
        return None
    except Exception as e:  # network, timeout
        print(f'  skip {path}: {e}', file=sys.stderr)
        return None


def repos_from_quests():
    names = []
    for line in open(QUESTS):
        m = re.match(r'\s*repo:\s*(\S+)\s*$', line)
        if m:
            names.append(m.group(1))
    return names


TRAILER = re.compile(r'^\s*(co-authored-by|signed-off-by|generated with|🤖)', re.I)


def first_line(text, limit=180):
    """Collapse a commit or release body to one clean line, minus git trailers."""
    if not text:
        return ''
    kept = [ln for ln in text.splitlines() if ln.strip() and not TRAILER.match(ln)]
    body = re.sub(r'\s+', ' ', re.sub(r'[#*`>\r]', '', ' '.join(kept))).strip()
    return body[:limit].rstrip() + ('...' if len(body) > limit else '')


def entries_for(repo):
    # private repos still get a changelog, but their commit URLs would 404 for
    # visitors, so links are dropped rather than published
    meta = api(f'repos/{OWNER}/{repo}') or {}
    public = not meta.get('private', False)
    rel = api(f'repos/{OWNER}/{repo}/releases?per_page={MAX_ENTRIES}')
    if rel:
        return [{'date': r['published_at'][:10],
                 'title': r.get('name') or r['tag_name'],
                 'body': first_line(r.get('body')),
                 'url': r['html_url'] if public else '',
                 'source': 'release'} for r in rel]
    commits = api(f'repos/{OWNER}/{repo}/commits?per_page={MAX_ENTRIES}')
    if not commits:
        return []
    out = []
    for c in commits:
        msg = c['commit']['message'].split('\n')
        out.append({'date': c['commit']['committer']['date'][:10],
                    'title': first_line(msg[0], 90),
                    'body': first_line('\n'.join(msg[1:])),
                    'url': c['html_url'] if public else '',
                    'source': 'commit'})
    return out


def yaml_str(s):
    return '"' + str(s).replace('\\', '\\\\').replace('"', '\\"') + '"'


def main():
    lines = ['# Generated by _scripts/refresh_quests.py. Do not edit by hand.']
    total = 0
    for repo in repos_from_quests():
        print(f'{repo}...', file=sys.stderr)
        items = entries_for(repo)
        if not items:
            continue
        lines.append(f'{repo}:')
        for e in items:
            lines.append(f'  - date: {yaml_str(e["date"])}')
            lines.append(f'    title: {yaml_str(e["title"])}')
            if e['body']:
                lines.append(f'    body: {yaml_str(e["body"])}')
            if e['url']:
                lines.append(f'    url: {yaml_str(e["url"])}')
            lines.append(f'    source: {yaml_str(e["source"])}')
        total += len(items)
    with open(OUT, 'w') as fh:
        fh.write('\n'.join(lines) + '\n')
    print(f'wrote {OUT} — {total} entries')


if __name__ == '__main__':
    main()
